-- 关键词初始数据。
-- 按分组扁平存放：facet 层级服务端从未实现过（旧接口一直返回空 facets），
-- 比例与清晰度的单选约束改由前端保证。

INSERT INTO keyword_groups (name, slug, description, is_parameter_group, sort_order, created_at) VALUES ('主体', 'subject', '先确定拍谁，再补身份和发型。大部分维度为单选，减少冲突。', 0, 1, datetime('now'));
INSERT INTO keywords (group_id, name, sort_order, created_at) VALUES
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '单人', 1, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '双人', 2, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '多人', 3, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '女性', 4, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '男性', 5, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '幼态', 6, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '年轻', 7, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '成熟', 8, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '中老年', 9, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '偏瘦', 10, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '匀称', 11, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '微胖', 12, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '健身型', 13, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '亚洲人', 14, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '欧美人', 15, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '模特', 16, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '学生', 17, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '职场人', 18, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '新娘', 19, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '运动型', 20, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '长发', 21, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '短发', 22, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '直发', 23, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '卷发', 24, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '高马尾', 25, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '黑长直', 26, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'subject'), '微卷长发', 27, datetime('now'));

INSERT INTO keyword_groups (name, slug, description, is_parameter_group, sort_order, created_at) VALUES ('环境', 'environment', '把地点、天气、时间和光线放在同一组里，符合拍摄思路。', 0, 2, datetime('now'));
INSERT INTO keywords (group_id, name, sort_order, created_at) VALUES
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '室内', 1, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '室外', 2, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '卧室', 3, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '床上', 4, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '沙发', 5, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '落地窗室内', 6, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '咖啡馆', 7, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '酒店房间', 8, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '白色影棚', 9, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '书店', 10, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '城市街头', 11, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '地铁站台', 12, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '商场中庭', 13, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '天台夜景', 14, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '海边沙滩', 15, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '森林小路', 16, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '草地', 17, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '雪地', 18, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '雨夜街道', 19, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '晴天', 20, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '阴天', 21, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '雨天', 22, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '雪天', 23, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '黄金时刻', 24, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '蓝调时刻', 25, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '夜景', 26, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '自然光', 27, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '窗边光', 28, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '侧光', 29, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '逆光', 30, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '侧逆光', 31, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '顶光', 32, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '柔光', 33, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '硬光', 34, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '漫射光', 35, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '霓虹光', 36, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'environment'), '烛光', 37, datetime('now'));

INSERT INTO keyword_groups (name, slug, description, is_parameter_group, sort_order, created_at) VALUES ('穿着与外观', 'outfit', '服装、配饰、妆容和画面质感放在一起，减少来回跳转。', 0, 3, datetime('now'));
INSERT INTO keywords (group_id, name, sort_order, created_at) VALUES
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '白衬衫', 1, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '黑衬衫', 2, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), 'T恤', 3, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '针织衫', 4, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '卫衣', 5, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '西装外套', 6, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '风衣', 7, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '牛仔外套', 8, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '吊带', 9, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '背心', 10, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '连衣裙', 11, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '半身裙', 12, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '百褶裙', 13, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '牛仔裤', 14, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '阔腿裤', 15, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '西装裤', 16, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '黑丝', 17, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '白丝袜', 18, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '长筒袜', 19, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '高跟鞋', 20, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '长靴', 21, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '运动鞋', 22, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '耳环', 23, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '项链', 24, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '眼镜', 25, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '裸感底妆', 26, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '清透底妆', 27, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '红唇', 28, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '粉唇', 29, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '眼线', 30, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '长睫毛', 31, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '湿发', 32, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '高清肤质', 33, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '胶片颗粒', 34, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '低饱和', 35, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '冷灰调', 36, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'outfit'), '暖黄调', 37, datetime('now'));

INSERT INTO keyword_groups (name, slug, description, is_parameter_group, sort_order, created_at) VALUES ('姿势与身体表现', 'pose', '告诉模型人物在做什么，以及重点刻画哪里。', 0, 4, datetime('now'));
INSERT INTO keywords (group_id, name, sort_order, created_at) VALUES
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '站立', 1, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '坐姿', 2, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '蹲姿', 3, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '行走', 4, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '靠墙', 5, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '回头', 6, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '低头', 7, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '抬手', 8, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '整理头发', 9, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '抱臂', 10, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '双手插袋', 11, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '单手扶栏杆', 12, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '看镜头', 13, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '看向远处', 14, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '面部', 15, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '眼神', 16, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '睫毛', 17, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '唇部', 18, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '牙齿', 19, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '锁骨', 20, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '肩颈', 21, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '腰线', 22, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '腿部线条', 23, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '手指', 24, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'pose'), '发丝', 25, datetime('now'));

INSERT INTO keyword_groups (name, slug, description, is_parameter_group, sort_order, created_at) VALUES ('拍摄方式', 'camera', '把焦段、景别、机位、构图放在一块，更符合摄影表达。', 0, 5, datetime('now'));
INSERT INTO keywords (group_id, name, sort_order, created_at) VALUES
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '24mm', 1, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '35mm', 2, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '50mm', 3, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '85mm', 4, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '135mm', 5, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '广角', 6, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '标准镜头', 7, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '长焦', 8, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '全身', 9, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '七分身', 10, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '半身', 11, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '近景', 12, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '面部特写', 13, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '局部特写', 14, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '平视', 15, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '仰拍', 16, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '俯拍', 17, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '低机位', 18, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '高机位', 19, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '居中构图', 20, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '三分法', 21, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '对角线构图', 22, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '引导线', 23, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '框景', 24, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '前景遮挡', 25, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '留白', 26, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '横向构图', 27, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '竖向构图', 28, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'camera'), '对称构图', 29, datetime('now'));

INSERT INTO keyword_groups (name, slug, description, is_parameter_group, sort_order, created_at) VALUES ('图片风格', 'style', '最后决定成片像照片、动漫还是插画。', 0, 6, datetime('now'));
INSERT INTO keywords (group_id, name, sort_order, created_at) VALUES
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '写实摄影', 1, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '电影写实', 2, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '商业广告', 3, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '日系写真', 4, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '韩系写真', 5, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '胶片摄影', 6, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '棚拍广告', 7, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '日漫风格', 8, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '美漫风格', 9, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '二次元插画', 10, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '国风插画', 11, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '扁平插画', 12, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '3D 渲染', 13, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '黏土风格', 14, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '像素风格', 15, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '冷淡', 16, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '温柔', 17, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '慵懒', 18, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '安静', 19, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '浪漫', 20, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '清冷', 21, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '明亮', 22, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '神秘', 23, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '干净', 24, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '松弛', 25, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '赛博霓虹', 26, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '胶片颗粒', 27, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '低饱和', 28, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '冷灰调', 29, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'style'), '暖黄调', 30, datetime('now'));

INSERT INTO keyword_groups (name, slug, description, is_parameter_group, sort_order, created_at) VALUES ('输出参数', 'output', '输出比例和清晰度参数，不再参与语义推理。', 1, 7, datetime('now'));
INSERT INTO keywords (group_id, name, sort_order, created_at) VALUES
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '1:1', 1, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '3:4', 2, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '4:3', 3, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '9:16', 4, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '16:9', 5, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '1024', 6, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '1536', 7, datetime('now')),
  ((SELECT id FROM keyword_groups WHERE slug = 'output'), '2048', 8, datetime('now'));
