name = "cf-text-to-image"
compatibility_date = "2025-06-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "txt2img-db"
database_id = "2d60db07-4ef5-4b7a-a0e1-25182556237f"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "txt2img-images"

[[queues.producers]]
binding = "TASK_QUEUE_A"
queue = "txt2img-task-queue-a"

[[queues.producers]]
binding = "TASK_QUEUE_B"
queue = "txt2img-task-queue-b"

[vars]
JWT_SECRET = "v1xpyobqemq4nvyblm3ev2irspcilq2a"
ENABLE_REGISTRATION = "true"
