name = "cf-text-to-image-task-consumer"
main = "task-consumer.ts"
compatibility_date = "2025-06-01"

[[d1_databases]]
binding = "DB"
database_name = "txt2img-db"
database_id = "2d60db07-4ef5-4b7a-a0e1-25182556237f"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "txt2img-images"

[observability]
enabled = true
head_sampling_rate = 1

[[queues.consumers]]
queue = "txt2img-task-queue"
max_batch_size = 1
max_batch_timeout = 0
max_retries = 1
max_concurrency = 10
